#!/bin/sh

DOTPATH=~/dotfiles

cd $DOTPATH

echo ' '\
'     _       _    __ _ _            '"\n" \
'  __| | ___ | |_ / _(_) | ___  ___  '"\n" \
' / _` |/ _ \| __| |_| | |/ _ \/ __| '"\n" \
'| (_| | (_) | |_|  _| | |  __/\__ \ '"\n" \
' \__,_|\___/ \__|_| |_|_|\___||___/ '"\n"


if [ $SHELL = "/bin/zsh" ]; then
  echo "Install Oh My Zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
if [ $SHELL = "/bin/bash" ]; then
  echo "Install Oh My Bash"
  bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
fi

for f in .??*
do
  [ "$f" = ".git" ] && continue
  [ "$f" = ".gitignore" ] && continue
  [ "$f" = ".config" ] && continue
  [ "$f" = ".DS_Store" ] && continue
  ln -snfv "$DOTPATH/$f" "$HOME/$f"
done

ln -snfv "$DOTPATH/bin" "$HOME/bin"

if [ -e $DOTPATH/private.d/etc/install ]; then
  echo "+++private.d"
  $DOTPATH/private.d/etc/install 
fi
