#!/bin/sh

DOTPATH=$(cd $(cd $(dirname $0) && pwd)/../ && pwd)
cd $DOTPATH

cat <<EOF
     _       _    __ _ _
  __| | ___ | |_ / _(_) | ___  ___
 / _\` |/ _ \| __| |_| | |/ _ \/ __|
| (_| | (_) | |_|  _| | |  __/\__ \\
 \__,_|\___/ \__|_| |_|_|\___||___/

EOF

# Install external modules
if [ $SHELL = "/bin/zsh" ]; then
  echo "Install Oh My Zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
if [ $SHELL = "/bin/bash" ]; then
  echo "Install Oh My Bash"
  bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
fi
if [ -d "$HOME/" ]; then
  bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
  curl -L https://raw.githubusercontent.com/ahmetb/kubectl-aliases/master/.kubectl_aliases -o ~/.kubectl_aliases
fi


for f in .??*
do
  [ "$f" = ".git" ] && continue
  [ "$f" = ".gitignore" ] && continue
  [ "$f" = ".config" ] && continue
  [ "$f" = ".DS_Store" ] && continue
  ln -snfv "$DOTPATH/$f" "$HOME/$f"
done

ln -snfv "$DOTPATH/bin" "$HOME/bin"

echo ""
echo "Create simbolic links from config.d/* to ~/.config/*"
$DOTPATH/etc/install_config.py

## Call private.d/etc/install
if [ -e $DOTPATH/private.d/etc/install ]; then
  echo "+++private.d"
  $DOTPATH/private.d/etc/install 
fi

